"""Removed optional enum

Revision ID: 4a447374386f
Revises: 8474d849e9d2
Create Date: 2025-03-16 19:41:59.246424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a447374386f'
down_revision = '8474d849e9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('READER', 'HR_MANAGER', 'IT_SUPPORT', 'EDITOR', 'ADMIN', name='userrole'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('READER', 'HR_MANAGER', 'IT_SUPPORT', 'EDITOR', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###
